spring.application.name=DevBoard

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/devboard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# JWT
jwt.secret=devboard_super_secret_key_change_this_in_production_minimum_256_bits
jwt.expiration=86400000